language: node_js
node_js:
- stable
notifications:
  slack:
    secure: aUtWXUUzf/tZE54cg5renwB0AswhYbcx5N45U0tCPUTYJ4UIgmLDNn2xU6yeVwSSf5itQKO5qTYAKa5rd2wr5RGJdZhav+Zsl+rhpfNLzl3hlkTWeuaYSoC8JLSBdGJ0KzSpFrzFomG2EfAEU7XsF2wsTXAfYNvpV8erQ9/c63c+Uy4g959VaudrFrqovxETx5labOvKwuHoVITWGx8WqCFHg/Eu1WsYMUZptU7EbPnAHyKk3aue0BRek+l0kmGsKlFwlLT3Pn1EdKZKdGpmczEePeFq1d4vgA0WSWeMG8jQvth3YSwdyXpbRIajiYWFY1OyFZnzy8aOg/fUTIH3O5z+H8UDeX4jwjGhIKnHXfr4dNg5uS4DJvE8nXhzDwFLOapfj+5RMfKsnDrS+MO5L6/ZSKL7pz6utqxyEc4O+JrrRBwIjlrUU3qcAseZVlUPutlhqSjjfyBMysBeYfOLbEdcgcTA4G8VOT0D7D1VJumV2UyBKjuXfqH1JpwJf2vJA15v5lFdAU0aefbvdUrWxyeLtsdBfs37el5Fo2q01me2KxAs8rAvxjAHQbtdI+b+0Junlbjfgqwb7VrD4rWeiN+xLw8y5iA4OB/JbGUQZ0MT0h1o5Kum6awpjpNo3tge+Cs5P/Zm38qFyUcsXEJ/isWt4og+hJg7t+56+tFRfEc=
deploy:
  skip_cleanup: true
  provider: npm
  email: steffen@kolmer.net
  api_key:
    secure: WScNBXM/SkuKNLxUq7j5ymplC6SzqKqRC+dTt+13GckkrCiIEUxSLY2G5KaQlX54qLubeB7sngl4RufGRng2p0VHDumsPT2BFb1QIzuEouqI+sq/2621Y0bxKFkdjMLMa7n5qklRMP051/DOVOsuvT3Thx+qwH381W7BwSVZol30dcbbCovAFD4tYaacAn/TAhtBmqi1RLZQuoF+/tl2xyEtCrD/50Q+GShu+9WgYJHU3m/sDq4OgxYd2kbY2FUtHv3U1TTHf4ywzq6O+YoCTDNgpm6En/hmQACVhIvVTmOWOh8qNF307SpsT7W05zH+P2iNYJl8pIv/WNYKYdZ4Qvo2L6hNkzYceC1tNQxWTJyWP14TaFmzEmGRqIUqOlVSxB1g56lE582QDnoohUy5AjuY9mGxUQMk/3XrhrixoRWl9beG9+pr8UmZBkpvIUa2SHKyCM+D80TXjhAnNOAEL3PoLyD2Bbcsp3DRhB1u+oc7d3ZJ+YYy8RtKzqFnnSfga9ImT780YfYZAd+dx+O3w1azvWMubcb7d9jProS1CGsoAYGEbs1mCgsLHo2rhSj3kzap39Q6+AgWfh6zeAq8Gy5qXevMV3v3GBFnsm+54KRikn1zqNqHwAB7E9KXbjOHzKE0zSZHvFcBhzbP3eobMbuHfkLgvonM65vf3DZ1Rvo=
  on:
    tags: true
    repo: skolmer/i18n-tag-schema